blank_issues_enabled: false
contact_links:
  - name: ðŸ“ƒ Documentation
    url: https://github.com/EhsanulHaqueSiam/StudentManagementSystem/wiki
    about: Don't know how or where to start? Check out our documentation!
  - name: ðŸ—¨ Discussions
    url: https://github.com/EhsanulHaqueSiam/StudentManagementSystem/discussions
    about: Got something you think should change or be added? Search for or start a new discussion!
